name: Terraform Apply

on:
  push:
    branches:
      - master
    paths:
      - "terraform/**"

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/environments/prod
        run: terraform init

      - name: Terraform Plan (log only)
        working-directory: terraform/environments/prod
        run: terraform plan -no-color

      - name: Terraform Apply
        working-directory: terraform/environments/prod
        run: terraform apply -auto-approve -input=false